package edu.umb.cs681.bankaccount;

public class MainRunnable {

    public static void main(String[] args) {
        ThreadSafeBankAccount2 safeBankAccount = new ThreadSafeBankAccount2();

        DepositRunnable depositRunnableOne = new DepositRunnable(safeBankAccount);
        Thread depositThreadOne = new Thread(depositRunnableOne);
        DepositRunnable depositRunnableTwo = new DepositRunnable(safeBankAccount);
        Thread depositThreadTwo = new Thread(depositRunnableTwo);
        DepositRunnable depositRunnableThree = new DepositRunnable(safeBankAccount);
        Thread depositThreadThree = new Thread(depositRunnableThree);
        DepositRunnable depositRunnableFour = new DepositRunnable(safeBankAccount);
        Thread depositThreadFour = new Thread(depositRunnableFour);
        DepositRunnable depositRunnableFive = new DepositRunnable(safeBankAccount);
        Thread depositThreadFive = new Thread(depositRunnableFive);
        DepositRunnable depositRunnableSix = new DepositRunnable(safeBankAccount);
        Thread depositThreadSix = new Thread(depositRunnableSix);
        DepositRunnable depositRunnableSeven = new DepositRunnable(safeBankAccount);
        Thread depositThreadSeven = new Thread(depositRunnableSeven);
        DepositRunnable depositRunnableEight = new DepositRunnable(safeBankAccount);
        Thread depositThreadEight = new Thread(depositRunnableEight);
        DepositRunnable depositRunnableNine = new DepositRunnable(safeBankAccount);
        Thread depositThreadNine = new Thread(depositRunnableNine);
        DepositRunnable depositRunnableTen = new DepositRunnable(safeBankAccount);
        Thread depositThreadTen = new Thread(depositRunnableTen);
        DepositRunnable depositRunnableEleven = new DepositRunnable(safeBankAccount);
        Thread depositThreadEleven = new Thread(depositRunnableEleven);
        DepositRunnable depositRunnableTwelve = new DepositRunnable(safeBankAccount);
        Thread depositThreadTwelve = new Thread(depositRunnableTwelve);
        DepositRunnable depositRunnableThirteen = new DepositRunnable(safeBankAccount);
        Thread depositThreadThirteen = new Thread(depositRunnableThirteen);
        DepositRunnable depositRunnableFourteen = new DepositRunnable(safeBankAccount);
        Thread depositThreadFourteen = new Thread(depositRunnableFourteen);

        WithdrawRunnable withdrawRunnableOne = new WithdrawRunnable(safeBankAccount);
        Thread withdrawThreadOne = new Thread(withdrawRunnableOne);
        WithdrawRunnable withdrawRunnableTwo = new WithdrawRunnable(safeBankAccount);
        Thread withdrawThreadTwo = new Thread(withdrawRunnableTwo);
        WithdrawRunnable withdrawRunnableThree = new WithdrawRunnable(safeBankAccount);
        Thread withdrawThreadThree = new Thread(withdrawRunnableThree);
        WithdrawRunnable withdrawRunnableFour = new WithdrawRunnable(safeBankAccount);
        Thread withdrawThreadFour = new Thread(withdrawRunnableFour);
        WithdrawRunnable withdrawRunnableFive = new WithdrawRunnable(safeBankAccount);
        Thread withdrawThreadFive = new Thread(withdrawRunnableFive);
        WithdrawRunnable withdrawRunnableSix = new WithdrawRunnable(safeBankAccount);
        Thread withdrawThreadSix = new Thread(withdrawRunnableSix);
        WithdrawRunnable withdrawRunnableSeven = new WithdrawRunnable(safeBankAccount);
        Thread withdrawThreadSeven = new Thread(withdrawRunnableSeven);
        WithdrawRunnable withdrawRunnableEight = new WithdrawRunnable(safeBankAccount);
        Thread withdrawThreadEight = new Thread(withdrawRunnableEight);
        WithdrawRunnable withdrawRunnableNine = new WithdrawRunnable(safeBankAccount);
        Thread withdrawThreadNine = new Thread(withdrawRunnableNine);
        WithdrawRunnable withdrawRunnableTen = new WithdrawRunnable(safeBankAccount);
        Thread withdrawThreadTen = new Thread(withdrawRunnableTen);
        WithdrawRunnable withdrawRunnableEleven = new WithdrawRunnable(safeBankAccount);
        Thread withdrawThreadEleven = new Thread(withdrawRunnableEleven);
        WithdrawRunnable withdrawRunnableTwelve = new WithdrawRunnable(safeBankAccount);
        Thread withdrawThreadTwelve = new Thread(withdrawRunnableTwelve);
        WithdrawRunnable withdrawRunnableThirteen = new WithdrawRunnable(safeBankAccount);
        Thread withdrawThreadThirteen = new Thread(withdrawRunnableThirteen);
        WithdrawRunnable withdrawRunnableFourteen = new WithdrawRunnable(safeBankAccount);
        Thread withdrawThreadFourteen = new Thread(withdrawRunnableFourteen);

        depositThreadOne.start();
        depositThreadTwo.start();
        depositThreadThree.start();
        depositThreadFour.start();
        depositThreadFive.start();
        depositThreadSix.start();
        depositThreadSeven.start();
        depositThreadEight.start();
        depositThreadNine.start();
        depositThreadTen.start();
        depositThreadEleven.start();
        depositThreadTwelve.start();
        depositThreadThirteen.start();
        depositThreadFourteen.start();
        withdrawThreadOne.start();
        withdrawThreadTwo.start();
        withdrawThreadThree.start();
        withdrawThreadFour.start();
        withdrawThreadFive.start();
        withdrawThreadSix.start();
        withdrawThreadSeven.start();
        withdrawThreadEight.start();
        withdrawThreadNine.start();
        withdrawThreadTen.start();
        withdrawThreadEleven.start();
        withdrawThreadTwelve.start();
        withdrawThreadThirteen.start();
        withdrawThreadFourteen.start();

        depositRunnableOne.setDone();
        withdrawRunnableOne.setDone();
        depositRunnableTwo.setDone();
        withdrawRunnableTwo.setDone();
        depositRunnableThree.setDone();
        withdrawRunnableThree.setDone();
        depositRunnableFour.setDone();
        withdrawRunnableFour.setDone();
        depositRunnableFive.setDone();
        withdrawRunnableFive.setDone();
        depositRunnableSix.setDone();
        withdrawRunnableSix.setDone();
        depositRunnableSeven.setDone();
        withdrawRunnableSeven.setDone();
        depositRunnableEight.setDone();
        withdrawRunnableEight.setDone();
        depositRunnableNine.setDone();
        withdrawRunnableNine.setDone();
        depositRunnableTen.setDone();
        withdrawRunnableTen.setDone();
        depositRunnableEleven.setDone();
        withdrawRunnableEleven.setDone();
        depositRunnableTwelve.setDone();
        withdrawRunnableTwelve.setDone();
        depositRunnableThirteen.setDone();
        withdrawRunnableThirteen.setDone();
        depositRunnableFourteen.setDone();
        withdrawRunnableFourteen.setDone();

        depositThreadOne.interrupt();
        depositThreadTwo.interrupt();
        depositThreadThree.interrupt();
        depositThreadFour.interrupt();
        depositThreadFive.interrupt();
        depositThreadSix.interrupt();
        depositThreadSeven.interrupt();
        depositThreadEight.interrupt();
        depositThreadNine.interrupt();
        depositThreadTen.interrupt();
        depositThreadEleven.interrupt();
        depositThreadTwelve.interrupt();
        depositThreadThirteen.interrupt();
        depositThreadFourteen.interrupt();
        withdrawThreadOne.interrupt();
        withdrawThreadTwo.interrupt();
        withdrawThreadThree.interrupt();
        withdrawThreadFour.interrupt();
        withdrawThreadFive.interrupt();
        withdrawThreadSix.interrupt();
        withdrawThreadSeven.interrupt();
        withdrawThreadEight.interrupt();
        withdrawThreadNine.interrupt();
        withdrawThreadTen.interrupt();
        withdrawThreadEleven.interrupt();
        withdrawThreadTwelve.interrupt();
        withdrawThreadThirteen.interrupt();
        withdrawThreadFourteen.interrupt();

        try {
            depositThreadOne.join();
            depositThreadTwo.join();
            depositThreadThree.join();
            depositThreadFour.join();
            depositThreadFive.join();
            depositThreadSix.join();
            depositThreadSeven.join();
            depositThreadEight.join();
            depositThreadNine.join();
            depositThreadTen.join();
            depositThreadEleven.join();
            depositThreadTwelve.join();
            depositThreadThirteen.join();
            depositThreadFourteen.join();
            withdrawThreadOne.join();
            withdrawThreadTwo.join();
            withdrawThreadThree.join();
            withdrawThreadFour.join();
            withdrawThreadFive.join();
            withdrawThreadSix.join();
            withdrawThreadSeven.join();
            withdrawThreadEight.join();
            withdrawThreadNine.join();
            withdrawThreadTen.join();
            withdrawThreadEleven.join();
            withdrawThreadTwelve.join();
            withdrawThreadThirteen.join();
            withdrawThreadFourteen.join();
        } catch (InterruptedException interruptedException) {
            System.out.println(interruptedException);
        }
    }

}
